# Generated by Django 3.1 on 2022-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
